name: "Get Cache Dependencies"
description: "get the dependencies and cache them using npm"
inputs:
 caching: 
  description: 'whether to chache dependencies or not'
  required: false
  default: 'true'
runs:
 using: 'composite' # check custom composite actions for more details
 steps: 
  #- name: Get code
    #uses: actions/checkout@v3
  - name: Cache dependencies
    if: inputs.caching == 'true' #if true following steps will be executed
    id: cache
    uses: actions/cache@v3
    with:
      path: node_modules
      key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
  - name: Install dependencies
    if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
    run: npm ci
    shell: bash
  